(defun mul_poly (P1 P2)
	(setf R '(0))
	(if (eq P1 '()) 
		(return-from mul_poly R)
	)
	(dotimes (i (length P2))
		(setf Q (mono_poly_mul P1 (create_mono (nth i P2) i)))
		(setf R (addition R Q))
	)
	(return-from mul_poly R)
)
